name: observable_ish
description: |
  Write elegant reactive cross-platform client side application using observable states and event emitters.
version: 6.0.2
homepage: https://github.com/Jaguar-dart/observable_ish
documentation:

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  collection: ^1.15.0

dev_dependencies:
  test: ^1.0.0
